routes/web.php
<?php

use Illuminate\Support\Facades\Route;

// Route::get('/', function () {
//     return view('welcome');
// });

Route::redirect('/', '/dashboard');

Route::middleware(['auth'])->group(function () {
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('/states', 'StateController');
    Route::resource('/townships', 'TownshipController');
    Route::resource('/centers', 'CenterController');
    Route::resource('/rooms', 'RoomController');
    Route::resource('/quarantineUser', 'QuarantineUserController');
    Route::resource('/volunteers', 'VolunteerController');
    Route::resource('/ondutys', 'OndutyController');
    Route::resource('/dutyOffs', 'DutyOffController');

    Route::get('/dashboard/state/{state}', 'DashboardController@state')->name('state');
    Route::get('/dashboard/township/{township}', 'DashboardController@township')->name('township');
    Route::get('/dashboard/center/{center}', 'DashboardController@center')->name('center');

    Route::get('/dashboard/center/{center}/patient', 'DashboardController@patient')->name('patient');
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/test', function () {
    $volunteers = App\Volunteer::unique();

    dd($volunteers);

});

app/DutyOff.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class DutyOff extends Model
{
    protected $dates = [
        'start_date',
        'end_date',
        'created_at',
        'updated_at',
    ];

    protected $fillable = [
        'start_date',
        'end_date',
        'volunteer_id',
    ];

    public function volunteer()
    {
        return $this->belongsTo('App\Volunteer', 'volunteer_id');
    }
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Center;
use App\QuarantineUser;
use App\Room;
use App\State;
use App\Township;
use App\Volunteer;

class DashboardController extends Controller
{
    public function index()
    {
        $states = State::all();

        $township = Township::all();
        $center = Center::all();
        $room = Room::all();
        $patient = QuarantineUser::all();
        $volunteer = Volunteer::all();

        return view('dashboard.index', [
            'states' => $states,
            'township' => count($township),
            'center' => count($center),
            'room' => count($room),
            'patient' => count($patient),
            'volunteer' => count($volunteer),
        ]);
    }

    public function state($state)
    {
        $townships = Township::where('state_id', $state)->get();

        $state = State::find($state);

        return view('dashboard.township', [
            'state' => $state,
            'townships' => $townships,
        ]);
    }

    public function township($township)
    {
        $centers = Center::where('township_id', $township)->get();

        $township = Township::find($township);

        return view('dashboard.center', [
            'centers' => $centers,
            'township' => $township,
        ]);

    }

    public function center($center)
    {
        $rooms = Room::where('center_id', $center)->get();

        $volunteers = Volunteer::where('center_id', $center)->get();

        $patients = QuarantineUser::where('center_id', $center)->get();

        $center = Center::find($center);

        return view('dashboard.singleCenter', [
            'rooms' => $rooms,
            'volunteers' => $volunteers,
            'center' => $center,
            'patients' => $patients,
        ]);
    }

    public function patient($center)
    {
        $quarantine_patients = QuarantineUser::FilterOn()->where('center_id', $center)->get();

        $center = Center::find($center);
        return view('dashboard.singlePatient', [
            'quarantine_patients' => $quarantine_patients,
            'center' => $center,
        ]);
    }
}

app/Http/Controllers/DutyOffController.php
<?php

namespace App\Http\Controllers;

use App\DutyOff;
use App\Http\Requests\DutyOffRequest;
use App\Volunteer;
use Illuminate\Http\Request;

class DutyOffController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $volunteers = Volunteer::all();
        return view('dashboard.dutyoff.index', [
            'volunteers' => $volunteers,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $volunteers = Volunteer::orderBy('volunteer_name', 'asc')->get();
        return view('dashboard.dutyoff.create', [
            'volunteers' => $volunteers,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(DutyOffRequest $request)
    {
        $dutyoff = DutyOff::create([
            'start_date' => $request->start_date,
            'end_date' => $request->end_date,
            'volunteer_id' => $request->volunteer_id,
        ]);

        $volunteer = $dutyoff->volunteer->volunteer_name;

        return back()->with('store', "$volunteer Added new On Duty Off");
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\DutyOff  $dutyOff
     * @return \Illuminate\Http\Response
     */
    public function show(DutyOff $dutyOff)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\DutyOff  $dutyOff
     * @return \Illuminate\Http\Response
     */
    public function edit(DutyOff $dutyOff)
    {

        $volunteers = Volunteer::orderBy('volunteer_name', 'asc')->get();
        return view('dashboard.dutyoff.edit', [
            'volunteers' => $volunteers,
            'dutyOff' => $dutyOff,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\DutyOff  $dutyOff
     * @return \Illuminate\Http\Response
     */
    public function update(DutyOffRequest $request, DutyOff $dutyOff)
    {
        $dutyOff->update([
            'start_date' => $request->start_date,
            'end_date' => $request->end_date,
            'volunteer_id' => $request->volunteer_id,
        ]);
        return redirect()->route('volunteers.show', $dutyOff->volunteer_id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\DutyOff  $dutyOff
     * @return \Illuminate\Http\Response
     */
    public function destroy(DutyOff $dutyOff)
    {
        $dutyOff->delete();
        return redirect()->route('volunteers.show', $dutyOff->volunteer_id);
    }
}

resources/views/dashboard/dutyoff/create.blade.php
@extends('dashboard.layouts.master')

@section('title', "Dashboard")

@section('content')
<div class="app-page-title">
    <div class="page-title-wrapper">
        <div class="page-title-heading">
            Add New Duty Off For Volunteers
        </div>
    </div>
  </div>

  @if ($errors->any())
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
    </div>
  @endif

  @if (session('store'))
    <div class="alert alert-success mb-5 alert-dismissible fade show" role="alert">
      <strong>{{session('store')}}</strong>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  @endif


      <div class="col-md-8 offset-md-2  border p-5 mt-5 mb-5 bg-light">
          <form action="{{route('dutyOffs.store')}}" method="post" >
            @csrf

            <div class="form-row">
            <div class="col-md-6 mb-3">
              <label for="start_date">Start Date *</label>
              <input type="date" class="form-control @error('start_date') border border-danger @enderror" id="start_date" name="start_date">
              @error("start_date")
              <small  class="mt-3 form-text text-danger">
                {{ $message }}
              </small>
              @enderror
            </div>
            <div class="col-md-6 mb-3">
              <label for="end_date">End Date *</label>
              <input type="date" class="form-control @error('end_date') border border-danger @enderror" id="end_date" name="end_date">
              @error("end_date")
              <small  class="mt-3 form-text text-danger">
                {{ $message }}
              </small>
              @enderror
            </div>
          </div>

          <div class="form-group">
            <label for="volunteer_id">Choose Volunteer</label>
            <select class="form-control" name="volunteer_id">
              @foreach($volunteers as $volunteer)
              <option value="{{$volunteer->id}}">
                {{$volunteer->volunteer_name}}
              </option>
              @endforeach
            </select>
          </div>

          <button type="submit" class="btn btn-primary">
            Add New Duty Off
          </button>
        </form>
      </div>

@endsection

resources/views/dashboard/dutyoff/edit.blade.php
@extends('dashboard.layouts.master')

@section('title', "Dashboard")

@section('content')
<div class="app-page-title">
    <div class="page-title-wrapper">
        <div class="page-title-heading">
            Edit Duty Off For Volunteers
        </div>
    </div>
  </div>

  @if ($errors->any())
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
    </div>
  @endif

  @if (session('store'))
    <div class="alert alert-success mb-5 alert-dismissible fade show" role="alert">
      <strong>{{session('store')}}</strong>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  @endif


      <div class="col-md-8 offset-md-2  border p-5 mt-5 mb-5 bg-light">
          <form action="{{route('dutyOffs.update', $dutyOff)}}" method="post" >
            @csrf
            @method('patch')
            <div class="form-row">
            <div class="col-md-6 mb-3">
              <label for="start_date">Start Date *</label>
              <input type="date" class="form-control @error('start_date') border border-danger @enderror" id="start_date" name="start_date" value="{{$dutyOff->start_date->format('Y-m-d')}}">
              @error("start_date")
              <small  class="mt-3 form-text text-danger">
                {{ $message }}
              </small>
              @enderror
            </div>
            <div class="col-md-6 mb-3">
              <label for="end_date">End Date *</label>
              <input type="date" class="form-control @error('end_date') border border-danger @enderror" id="end_date" name="end_date" value="{{$dutyOff->end_date->format('Y-m-d')}}">
              @error("end_date")
              <small  class="mt-3 form-text text-danger">
                {{ $message }}
              </small>
              @enderror
            </div>
          </div>

          <div class="form-group">
            <label for="volunteer_id">Choose Volunteer</label>
            <select class="form-control" name="volunteer_id">
              @foreach($volunteers as $volunteer)
              <option value="{{$volunteer->id}}"
                @if($volunteer->id == $dutyOff->volunteer_id)
                  selected
                @endif
              >
                {{$volunteer->volunteer_name}}
              </option>
              @endforeach
            </select>
          </div>

          <button type="submit" class="btn btn-primary">
            Update Duty Off
          </button>
        </form>
      </div>

@endsection

resources/views/dashboard/dutyoff/index.blade.php
@extends('dashboard.layouts.master')

@section('title', "Dashboard")

@section('content')
<div class="app-page-title">
    <div class="page-title-wrapper">
        <div class="page-title-heading">
                Duty Off List
        </div>
        <div class="page-title-actions">
            <a href="{{route('volunteers.create')}}" class="mr-3 btn btn-primary text-light" >
                <i class="pe-7s-note font-size-xl "> </i> Add New Duty Off
            </a>
        </div>
    </div>
</div>

@if (session('store'))
<div class="alert alert-success mb-5 alert-dismissible fade show" role="alert">
  <strong>{{session('store')}}</strong>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
@endif

@if (session('update'))
<div class="alert alert-success mb-5 alert-dismissible fade show" role="alert">
  <strong>{{session('update')}}</strong>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
@endif

@if (session('delete'))
<div class="alert alert-danger mb-5 alert-dismissible fade show" role="alert">
  <strong>{{session('delete')}}</strong>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
@endif


  <table id="volunteer" class="table table-striped table-bordered mt-4 mb-4" style="width:100%">
    <thead>
      <tr>
        <th>ID</th>
        <th>Profile</th>
        <th>Volunteer Name</th>
        <th>On Duty Duration</th>
        <th>Duty Off Duration</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
        @foreach($volunteers as $volunteer)
        <tr>
            <td>{{$volunteer->id}}</td>
            <td>
                <img src="{{url('storage/'.str_replace('public/', '', $volunteer->profile_image))}}" alt="{{$volunteer->volunteer_name}}" style="width: 70px; height: 70px">
            </td>
            <td>{{$volunteer->volunteer_name}}</td>
            <td>
              @foreach($volunteer->ondutys as $volunteerOnDuty)
                <div>
                  {{$volunteerOnDuty->entry_date->format('d/m/Y')}} -
                  {{$volunteerOnDuty->leave_date->format('d/m/Y')}}
                </div>
              @endforeach
            </td>
            <td>
              @foreach($volunteer->dutyoffs as $volunteerDutyOff)
                <div>
                  {{$volunteerDutyOff->start_date->format('d/m/Y')}} -
                  {{$volunteerDutyOff->end_date->format('d/m/Y')}}
                </div>
              @endforeach
            </td>
            <td>
                <a href="{{route('volunteers.show', $volunteer->id)}}" class="ml-3 text-info font-size-lg" title="Show Patient">
                    <i class="pe-7s-monitor"> </i>
                </a>
                <!-- <a href="{{route('volunteers.edit', $volunteer->id)}}" class="ml-3 text-info font-size-lg" title="Edit Patient">
                    <i class="pe-7s-note2"> </i>
                </a>
                <form action="{{ route('volunteers.destroy', $volunteer->id) }}" onsubmit="return confirm('{{ 'Are You Sure' }}');" method="POST" class="d-inline">
                  @csrf
                  @method('DELETE')
                  <button type="submit" class="btn btn-link" title="Delete Patient">
                    <i class="metismenu-icon pe-7s-trash h5 text-danger" ></i>
                  </button>
              </form> -->
            </td>
        </tr>
        @endforeach
    </tbody>
    <tfoot>
    <tr>
        <th>ID</th>
        <th>Profile</th>
        <th>Volunteer Name</th>
        <th>Action</th>
      </tr>
    </tfoot>
  </table>



@endsection

@section('script')
  <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
  <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
  <script>
    $(document).ready(function () {
      $('#volunteer').DataTable();
    });
  </script>
  @endsection