routes/web.php
<?php

use Illuminate\Support\Facades\Route;

// Route::get('/', function () {
//     return view('welcome');
// });

Route::redirect('/', '/dashboard');

Route::middleware(['auth'])->group(function () {
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('/states', 'StateController');
    Route::resource('/townships', 'TownshipController');
    Route::resource('/centers', 'CenterController');
    Route::resource('/rooms', 'RoomController');
    Route::resource('/quarantineUser', 'QuarantineUserController');
    Route::resource('/volunteers', 'VolunteerController');
    Route::resource('/ondutys', 'OndutyController');
    Route::resource('/dutyOffs', 'DutyOffController');

    Route::get('/dashboard/state/{state}', 'DashboardController@state')->name('state');
    Route::get('/dashboard/township/{township}', 'DashboardController@township')->name('township');
    Route::get('/dashboard/center/{center}', 'DashboardController@center')->name('center');

    Route::get('/dashboard/center/{center}/patient', 'DashboardController@patient')->name('patient');
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/test', function () {
    $volunteers = App\Volunteer::unique();

    dd($volunteers);

});

app/Volunteer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Volunteer extends Model
{

    protected $fillable = [
        'volunteer_name',
        'phone',
        'address',
        'image',
        'center_id',
    ];

    public function center()
    {
        return $this->belongsTo('App\Center', 'center_id');
    }

    public function ondutys()
    {
        return $this->hasMany('App\Onduty', 'volunteer_id');
    }

    public function dutyoffs()
    {
        return $this->hasMany('App\DutyOff', 'volunteer_id');
    }
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Center;
use App\QuarantineUser;
use App\Room;
use App\State;
use App\Township;
use App\Volunteer;

class DashboardController extends Controller
{
    public function index()
    {
        $states = State::all();

        $township = Township::all();
        $center = Center::all();
        $room = Room::all();
        $patient = QuarantineUser::all();
        $volunteer = Volunteer::all();

        return view('dashboard.index', [
            'states' => $states,
            'township' => count($township),
            'center' => count($center),
            'room' => count($room),
            'patient' => count($patient),
            'volunteer' => count($volunteer),
        ]);
    }

    public function state($state)
    {
        $townships = Township::where('state_id', $state)->get();

        $state = State::find($state);

        return view('dashboard.township', [
            'state' => $state,
            'townships' => $townships,
        ]);
    }

    public function township($township)
    {
        $centers = Center::where('township_id', $township)->get();

        $township = Township::find($township);

        return view('dashboard.center', [
            'centers' => $centers,
            'township' => $township,
        ]);

    }

    public function center($center)
    {
        $rooms = Room::where('center_id', $center)->get();

        $volunteers = Volunteer::where('center_id', $center)->get();

        $patients = QuarantineUser::where('center_id', $center)->get();

        $center = Center::find($center);

        return view('dashboard.singleCenter', [
            'rooms' => $rooms,
            'volunteers' => $volunteers,
            'center' => $center,
            'patients' => $patients,
        ]);
    }

    public function patient($center)
    {
        $quarantine_patients = QuarantineUser::FilterOn()->where('center_id', $center)->get();

        $center = Center::find($center);
        return view('dashboard.singlePatient', [
            'quarantine_patients' => $quarantine_patients,
            'center' => $center,
        ]);
    }
}

app/Http/Controllers/VolunteerController.php
<?php

namespace App\Http\Controllers;

use App\Center;
use App\Http\Requests\VolunteerRequest;
use App\Volunteer;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class VolunteerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $volunteers = Volunteer::all();
        return view('dashboard.volunteer.index', [
            'volunteers' => $volunteers,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $centers = Center::orderBy('center_name', 'asc')->get();
        return view('dashboard.volunteer.create', [
            'centers' => $centers,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(VolunteerRequest $request)
    {

        $path = "";
        if ($request->image) {
            $path = $request->file('image')->store('public/image');
        } else {
            $path = "public/image/user.png";
        }

        $volunteer = new Volunteer();
        $volunteer->volunteer_name = $request->volunteer_name;
        $volunteer->profile_image = $path;
        $volunteer->phone = $request->phone;
        $volunteer->address = $request->address;
        $volunteer->center_id = $request->center_id;
        $volunteer->save();

        return redirect()->route('volunteers.index')->with('store', "$volunteer->volunteer_name 's information Stored!!!");
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\volunteer  $volunteer
     * @return \Illuminate\Http\Response
     */
    public function show(volunteer $volunteer)
    {
        return view('dashboard.volunteer.show', [
            'volunteer' => $volunteer,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\volunteer  $volunteer
     * @return \Illuminate\Http\Response
     */
    public function edit(volunteer $volunteer)
    {
        $centers = Center::orderBy('center_name', 'asc')->get();
        return view('dashboard.volunteer.edit', [
            'centers' => $centers,
            'volunteer' => $volunteer,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\volunteer  $volunteer
     * @return \Illuminate\Http\Response
     */
    public function update(VolunteerRequest $request, volunteer $volunteer)
    {
        if ($request->image) {
            $path = $request->file('image')->store('public/image');
            $volunteer->profile_image = $path;
        }

        $volunteer->volunteer_name = $request->volunteer_name;
        $volunteer->phone = $request->phone;
        $volunteer->address = $request->address;
        $volunteer->center_id = $request->center_id;
        $volunteer->update();

        return redirect()->route('volunteers.index')->with('update', "$volunteer->volunteer_name 's information Updated!!!");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\volunteer  $volunteer
     * @return \Illuminate\Http\Response
     */
    public function destroy(volunteer $volunteer)
    {
        $volunteer->delete();
        return redirect()->route('volunteers.index')->with('delete', "$volunteer->volunteer_name 's information Delete!!!");
    }
}

resources/views/dashboard/volunteer/create.blade.php
@extends('dashboard.layouts.master')

@section('title', "Dashboard")

@section('content')
<div class="app-page-title">
    <div class="page-title-wrapper">
        <div class="page-title-heading">
            Add New Volunteer
        </div>
        <div class="page-title-actions">
            <a href="{{route('volunteers.index')}}" class="mr-3 btn btn-primary text-light" >
                <i class="pe-7s-back font-size-xl "> </i> Back To Volunteer List
            </a>
        </div>
    </div>
  </div>

  @if ($errors->any())
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
    </div>
@endif

      <div class="col-md-8 offset-md-2  border p-5 mt-5 mb-5 bg-light">
          <form action="{{route('volunteers.store')}}" method="post" enctype="multipart/form-data">
            @csrf
          <div class="form-group">
            <label for="volunteer_name" class="h5">Volunteer Name *</label>
            <input type="text" class="form-control @error('volunteer_name') border border-danger @enderror" id="volunteer_name" placeholder="Enter Volunteer Name" name="volunteer_name">
            @error("volunteer_name")
            <small  class="mt-3 form-text text-danger">
              {{ $message }}
            </small>
            @enderror
          </div>

          <label for="image" class="h5">Profile Image</label>
          <div class="custom-file mb-3">
            <input type="file" class="custom-file-input" id="validatedCustomFile" name="image">
            <label class="custom-file-label" for="validatedCustomFile">Choose profile...</label>
          </div>

          <div class="form-group">
            <label for="phone" class="h5">Phone No.</label>
            <input type="text" class="form-control @error('phone') border border-danger @enderror" id="phone" placeholder="Enter Phone No." name="phone">
            @error("phone")
            <small  class="mt-3 form-text text-danger">
              {{ $message }}
            </small>
            @enderror
          </div>

          <div class="form-group">
            <label for="address" class="h5">Address *</label>
            <textarea name="address" rows="7" class="form-control @error('address') border border-danger @enderror" id="address" placeholder="Enter address"></textarea>
            <!-- <input type="text" class="form-control @error('phone') border border-danger @enderror" id="phone" placeholder="Enter Phone No." name="phone"> -->
            @error("address")
            <small  class="mt-3 form-text text-danger">
              {{ $message }}
            </small>
            @enderror
          </div>

          <div class="form-group">
            <label for="center_id">Choose Quarantine Center</label>
            <select class="form-control" name="center_id">
              @foreach($centers as $center)
              <option onclick="test()" value="{{$center->id}}">
                {{$center->center_name}}
              </option>
              @endforeach
            </select>
          </div>

          <button type="submit" class="btn btn-primary">
            Add New Volunteer
          </button>
        </form>
      </div>

@endsection

resources/views/dashboard/volunteer/edit.blade.php
@extends('dashboard.layouts.master')

@section('title', "Dashboard")

@section('content')
<div class="app-page-title">
    <div class="page-title-wrapper">
        <div class="page-title-heading">
            Edit Volunteer
        </div>
        <div class="page-title-actions">
            <a href="{{route('volunteers.index')}}" class="mr-3 btn btn-primary text-light" >
                <i class="pe-7s-back font-size-xl "> </i> Back To Volunteer List
            </a>
        </div>
    </div>
  </div>

  @if ($errors->any())
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
    </div>
@endif

      <div class="col-md-8 offset-md-2  border p-5 mt-5 mb-5 bg-light">
          <form action="{{route('volunteers.update', $volunteer->id)}}" method="post" enctype="multipart/form-data">
            @csrf
            @method('patch')
          <div class="form-group">
            <label for="volunteer_name" class="h5">Volunteer Name *</label>
            <input type="text" class="form-control @error('volunteer_name') border border-danger @enderror" id="volunteer_name" placeholder="Enter Volunteer Name" name="volunteer_name" value="{{$volunteer->volunteer_name}}">
            @error("volunteer_name")
            <small  class="mt-3 form-text text-danger">
              {{ $message }}
            </small>
            @enderror
          </div>

          <img src="{{url('storage/'.str_replace('public/', '', $volunteer->profile_image))}}" alt="{{$volunteer->volunteer_name}}" style="width: 70px; height: 70px; display: block; border: 1px solid gray;">
          <label for="image" class="h5 mt-2">Profile Image</label>
          <div class="custom-file mb-3">
            <input type="file" class="custom-file-input" id="validatedCustomFile" name="image">
            <label class="custom-file-label" for="validatedCustomFile">Choose profile...</label>
          </div>

          <div class="form-group">
            <label for="phone" class="h5">Phone No.</label>
            <input type="text" class="form-control @error('phone') border border-danger @enderror" id="phone" placeholder="Enter Phone No." name="phone" value="{{$volunteer->phone}}">
            @error("phone")
            <small  class="mt-3 form-text text-danger">
              {{ $message }}
            </small>
            @enderror
          </div>

          <div class="form-group">
            <label for="address" class="h5">Address *</label>
            <textarea name="address" rows="7" class="form-control @error('address') border border-danger @enderror" id="address" placeholder="Enter address">{{$volunteer->address}}</textarea>
            @error("address")
            <small  class="mt-3 form-text text-danger">
              {{ $message }}
            </small>
            @enderror
          </div>

          <div class="form-group">
            <label for="center_id">Choose Quarantine Center</label>
            <select class="form-control" name="center_id">
              @foreach($centers as $center)
              <option onclick="test()" value="{{$center->id}}"
                @if($center->id === $volunteer->center_id)
                  selected
                @endif
              >
                {{$center->center_name}}
              </option>
              @endforeach
            </select>
          </div>

          <button type="submit" class="btn btn-primary">
            Edit Volunteer
          </button>
        </form>
      </div>

@endsection

resources/views/dashboard/volunteer/index.blade.php
@extends('dashboard.layouts.master')

@section('title', "Dashboard")

@section('content')
<div class="app-page-title">
    <div class="page-title-wrapper">
        <div class="page-title-heading">
            <div>
                Quarantine (Volunteer) Lists
            </div>
        </div>
        <div class="page-title-actions">
            <a href="{{route('volunteers.create')}}" class="mr-3 btn btn-primary text-light" >
                <i class="pe-7s-note font-size-xl "> </i> Add New Volunteer
            </a>
        </div>
    </div>
</div>

@if (session('store'))
<div class="alert alert-success mb-5 alert-dismissible fade show" role="alert">
  <strong>{{session('store')}}</strong>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
@endif

@if (session('update'))
<div class="alert alert-success mb-5 alert-dismissible fade show" role="alert">
  <strong>{{session('update')}}</strong>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
@endif

@if (session('delete'))
<div class="alert alert-danger mb-5 alert-dismissible fade show" role="alert">
  <strong>{{session('delete')}}</strong>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
@endif

  <table id="volunteer" class="table table-striped table-bordered mt-4 mb-4" style="width:100%">
    <thead>
      <tr>
        <th>ID</th>
        <th>Profile</th>
        <th>Volunteer Name</th>
        <th>Phone</th>
        <th>Address</th>
        <th>Center</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
        @foreach($volunteers as $volunteer)
        <tr>
            <td>{{$volunteer->id}}</td>
            <td>
                <img src="{{url('storage/'.str_replace('public/', '', $volunteer->profile_image))}}" alt="{{$volunteer->volunteer_name}}" style="width: 70px; height: 70px">
            </td>
            <td>{{$volunteer->volunteer_name}}</td>
            <td>{{$volunteer->phone}}</td>
            <td>{{$volunteer->address}}</td>
            <td>{{$volunteer->center->center_name}}</td>
            <td>
                <a href="{{route('volunteers.show', $volunteer->id)}}" class="ml-3 text-info h4" title="Show Patient">
                    <i class="pe-7s-monitor"> </i>
                </a> <br>
                <a href="{{route('volunteers.edit', $volunteer->id)}}" class="ml-3 text-info font-size-lg" title="Edit Patient">
                    <i class="pe-7s-note2"> </i>
                </a> <br>
                <form action="{{ route('volunteers.destroy', $volunteer->id) }}" onsubmit="return confirm('{{ 'Are You Sure' }}');" method="POST" class="d-inline">
                  @csrf
                  @method('DELETE')
                  <button type="submit" class="btn btn-link" title="Delete Patient">
                    <i class="metismenu-icon pe-7s-trash h5 text-danger" ></i>
                  </button>
              </form>
            </td>
        </tr>
        @endforeach
    </tbody>
    <tfoot>
    <tr>
    <th>ID</th>
        <th>Profile</th>
        <th>Volunteer Name</th>
        <th>Phone</th>
        <th>Address</th>
        <th>Center</th>
        <th>Action</th>
      </tr>
    </tfoot>
  </table>


  @endsection
  @section('script')
  <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
  <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
  <script>
    $(document).ready(function () {
      $('#volunteer').DataTable();
    });
  </script>
  @endsection

resources/views/dashboard/volunteer/show.blade.php
@extends('dashboard.layouts.master')

@section('title', "Dashboard")

@section('content')
<div class="app-page-title">
  <div class="page-title-wrapper">
      <div class="page-title-heading">
          Volunteer Profile
      </div>
      <!-- <div class="page-title-actions">
          <a href="{{route('volunteers.index')}}" class="mr-3 btn btn-primary text-light" >
              <i class="pe-7s-back font-size-xl "> </i> Back To Volunteer List
          </a>
      </div> -->
  </div>
</div>

<div class="row">
  <div class="col-md-3 col-sm-4">
    <div class="card">
      <img src="{{url('storage/'.str_replace('public/', '', $volunteer->profile_image))}}" class="card-img-top" alt="{{$volunteer->volunteer_name}}">
    </div>
  </div>
  <div class="col-md-8 col-sm-8">
  <div class="main-card mb-3 card">
      <div class="card-header">
          About - {{$volunteer->volunteer_name}}
          <div class="btn-actions-pane-right">
              <div role="group" class="btn-group-sm btn-group">
                  <a href="#onduty" class="btn btn-success">Onduty</a>
                  <a href="#dutyoff" class="btn btn-danger">Duty Off</a>
              </div>
          </div>
      </div>
      <div class="table-responsive">
          <table class="align-middle mb-0 table table-borderless table-striped table-hover">
              <thead>

              </thead>
              <tbody>
              <tr>
                    <th>ID</th>
                    <td>#{{$volunteer->id}}</t>
                </tr>
              <tr>
                  <th>Volunteer Name</th>
                  <td>{{$volunteer->volunteer_name}}</t>
              </tr>
              <tr>
                  <th>Phone No.</td>
                  <td>{{$volunteer->phone}}</t>
              </tr>
              <tr>
                  <th>Address</td>
                  <td>{{$volunteer->address}}</t>
              </tr>
              <tr>
                  <th>Quarantine Center</td>
                  <td>{{$volunteer->center->center_name}}</t>
              </tr>
              <tr>
                  <th>Township</td>
                  <td>{{$volunteer->center->township->township_name}}</t>
              </tr>
              <tr>
                  <th>Region / State</td>
                  <td>{{$volunteer->center->township->state->state_name}}</t>
              </tr>
              </tbody>
          </table>
      </div>
      <div class="d-block text-center card-footer">
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem sed cum illo quae, asperiores quam voluptates quo assumenda iure eos ducimus sapiente placeat similique molestias in provident error ipsum dicta?</p>
      </div>
  </div>
  </div>
</div>

<div class="divider mt-5 mb-5"></div>

<div id="onduty"></div>
<div id="dutyoff"></div>

<ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
  <li class="nav-item" role="presentation">
    <a class="nav-link active btn btn-success mr-2" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">Onduty Record</a>
  </li>
  <li class="nav-item" role="presentation">
    <a class="nav-link btn btn-danger ml-2" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">Duty Off Record</a>
  </li>
</ul>
<div class="tab-content" id="pills-tabContent">
  <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
  <table id="volunteer" class="table table-striped table-bordered mt-5 mb-5" style="width:100%">
    <thead>
      <tr class="bg-success text-light">
        <th>ID</th>
        <th>On Duty Duration</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
        @foreach($volunteer->ondutys as $volunteerOnduty)
        <tr>
            <td>
                {{$volunteerOnduty->id}}
            </td>
            <td>
                <span>
                    {{$volunteerOnduty->entry_date->format('d/m/Y')}} -
                    {{$volunteerOnduty->leave_date->format('d/m/Y')}}
                </span>
            </td>
            <td>
                <a href="{{route('ondutys.edit', $volunteerOnduty->id)}}" class="ml-3 text-info font-size-lg" title="Edit Duty On">
                    <i class="pe-7s-note2"> </i>
                </a>
                <form action="{{ route('ondutys.destroy', $volunteerOnduty->id) }}" onsubmit="return confirm('{{ 'Are You Sure' }}');" method="POST" class="d-inline">
                  @csrf
                  @method('DELETE')
                  <button type="submit" class="btn btn-link" title="Delete Duty On">
                    <i class="metismenu-icon pe-7s-trash h5 text-danger" ></i>
                  </button>
              </form>
            </td>
        </tr>
        @endforeach

    </tbody>
    <tfoot>
    <tr>
        <th>ID</th>
        <th>On Duty Duration</th>
        <th>Action</th>
      </tr>
    </tfoot>
  </table>

  </div>
  <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
    <table id="volunteer" class="table table-striped table-bordered mt-5 mb-5" style="width:100%">
        <thead>
        <tr class="bg-danger text-light">
            <th>ID</th>
            <th>Duty Off Duration</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
            @foreach($volunteer->dutyoffs as $volunteerDutyOff)
            <tr>
                <td>
                    {{$volunteerDutyOff->id}}
                </td>
                <td>
                    <span>
                        {{$volunteerDutyOff->start_date->format('d/m/Y')}} -
                        {{$volunteerDutyOff->end_date->format('d/m/Y')}}
                    </span>
                </td>
                <td>
                    <a href="{{route('dutyOffs.edit', $volunteerDutyOff->id)}}" class="ml-3 text-info font-size-lg" title="Edit Duty Off">
                    <i class="pe-7s-note2"> </i>
                    </a>
                    <form action="{{ route('dutyOffs.destroy', $volunteerDutyOff->id) }}" onsubmit="return confirm('{{ 'Are You Sure' }}');" method="POST" class="d-inline">
                  @csrf
                  @method('DELETE')
                  <button type="submit" class="btn btn-link" title="Delete Duty Off">
                    <i class="metismenu-icon pe-7s-trash h5 text-danger" ></i>
                  </button>
              </form>
                </td>
            </tr>
            @endforeach
        </tbody>
        <tfoot>
        <tr>
            <th>ID</th>
            <th>Duty Off Duration</th>
            <th>Action</th>
        </tr>
        </tfoot>
    </table>

  </div>
</div>

@endsection