routes/web.php
<?php

use Illuminate\Support\Facades\Route;

// Route::get('/', function () {
//     return view('welcome');
// });

Route::redirect('/', '/dashboard');

Route::middleware(['auth'])->group(function () {
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('/states', 'StateController');
    Route::resource('/townships', 'TownshipController');
    Route::resource('/centers', 'CenterController');
    Route::resource('/rooms', 'RoomController');
    Route::resource('/quarantineUser', 'QuarantineUserController');
    Route::resource('/volunteers', 'VolunteerController');
    Route::resource('/ondutys', 'OndutyController');
    Route::resource('/dutyOffs', 'DutyOffController');

    Route::get('/dashboard/state/{state}', 'DashboardController@state')->name('state');
    Route::get('/dashboard/township/{township}', 'DashboardController@township')->name('township');
    Route::get('/dashboard/center/{center}', 'DashboardController@center')->name('center');

    Route::get('/dashboard/center/{center}/patient', 'DashboardController@patient')->name('patient');
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/test', function () {
    $volunteers = App\Volunteer::unique();

    dd($volunteers);

});

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Center;
use App\QuarantineUser;
use App\Room;
use App\State;
use App\Township;
use App\Volunteer;

class DashboardController extends Controller
{
    public function index()
    {
        $states = State::all();

        $township = Township::all();
        $center = Center::all();
        $room = Room::all();
        $patient = QuarantineUser::all();
        $volunteer = Volunteer::all();

        return view('dashboard.index', [
            'states' => $states,
            'township' => count($township),
            'center' => count($center),
            'room' => count($room),
            'patient' => count($patient),
            'volunteer' => count($volunteer),
        ]);
    }

    public function state($state)
    {
        $townships = Township::where('state_id', $state)->get();

        $state = State::find($state);

        return view('dashboard.township', [
            'state' => $state,
            'townships' => $townships,
        ]);
    }

    public function township($township)
    {
        $centers = Center::where('township_id', $township)->get();

        $township = Township::find($township);

        return view('dashboard.center', [
            'centers' => $centers,
            'township' => $township,
        ]);

    }

    public function center($center)
    {
        $rooms = Room::where('center_id', $center)->get();

        $volunteers = Volunteer::where('center_id', $center)->get();

        $patients = QuarantineUser::where('center_id', $center)->get();

        $center = Center::find($center);

        return view('dashboard.singleCenter', [
            'rooms' => $rooms,
            'volunteers' => $volunteers,
            'center' => $center,
            'patients' => $patients,
        ]);
    }

    public function patient($center)
    {
        $quarantine_patients = QuarantineUser::FilterOn()->where('center_id', $center)->get();

        $center = Center::find($center);
        return view('dashboard.singlePatient', [
            'quarantine_patients' => $quarantine_patients,
            'center' => $center,
        ]);
    }
}

resources/views/dashboard/quser/create.blade.php
@extends('dashboard.layouts.master')

@section('title', "Dashboard")

@section('content')
<div class="app-page-title">
    <div class="page-title-wrapper">
        <div class="page-title-heading">
            Add New Patient
        </div>
        <div class="page-title-actions">
            <a href="{{route('quarantineUser.index')}}" class="mr-3 btn btn-primary text-light" >
                <i class="pe-7s-back font-size-xl "> </i> Back To Patients List
            </a>
        </div>
    </div>
  </div>

  @if ($errors->any())
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
    </div>
@endif

      <div class="col-md-8 offset-md-2  border p-5 mt-5 bg-light">
          <form action="{{route('quarantineUser.store')}}" method="post" enctype="multipart/form-data">
            @csrf
          <div class="form-group">
            <label for="quser_name" class="h5">Patient Name *</label>
            <input type="text" class="form-control @error('quser_name') border border-danger @enderror" id="quser_name" placeholder="Enter Patient Name" name="quser_name">
            @error("quser_name")
            <small  class="mt-3 form-text text-danger">
              {{ $message }}
            </small>
            @enderror
          </div>

          <label for="image" class="h5">Profile Image</label>
          <div class="custom-file mb-3">
            <input type="file" class="custom-file-input" id="validatedCustomFile" name="image">
            <label class="custom-file-label" for="validatedCustomFile">Choose profile...</label>
          </div>

          <div class="form-group">
            <label for="phone" class="h5">Phone No.</label>
            <input type="text" class="form-control @error('phone') border border-danger @enderror" id="phone" placeholder="Enter Phone No." name="phone">
            @error("phone")
            <small  class="mt-3 form-text text-danger">
              {{ $message }}
            </small>
            @enderror
          </div>

          <div class="form-group">
            <label for="address" class="h5">Address *</label>
            <textarea name="address" rows="7" class="form-control @error('address') border border-danger @enderror" id="address" placeholder="Enter address"></textarea>
            <!-- <input type="text" class="form-control @error('phone') border border-danger @enderror" id="phone" placeholder="Enter Phone No." name="phone"> -->
            @error("address")
            <small  class="mt-3 form-text text-danger">
              {{ $message }}
            </small>
            @enderror
          </div>

          <div class="form-row">
            <div class="col-md-6 mb-3">
              <label for="entry_date">Entry Date *</label>
              <input type="date" class="form-control @error('entry_date') border border-danger @enderror" id="entry_date" name="entry_date">
              @error("entry_date")
              <small  class="mt-3 form-text text-danger">
                {{ $message }}
              </small>
              @enderror
            </div>
            <div class="col-md-6 mb-3">
              <label for="leave_date">Leave Date *</label>
              <input type="date" class="form-control @error('leave_date') border border-danger @enderror" id="leave_date" name="leave_date">
              @error("leave_date")
              <small  class="mt-3 form-text text-danger">
                {{ $message }}
              </small>
              @enderror
            </div>
          </div>

          <div class="form-group">
            <label for="remark" class="h5">Remark</label>
            <textarea name="remark" rows="7" class="form-control @error('remark') border border-danger @enderror" id="remark" placeholder="Enter remark"></textarea>

            @error("remark")
            <small  class="mt-3 form-text text-danger">
              {{ $message }}
            </small>
            @enderror
          </div>

          <div>
            <patient-add-component :centers="{{$centers}}" :rooms="{{$rooms}}"/>
          </div>
          @error("room_id")
            <small  class="mt-3 mb-3 form-text text-danger">
              Choose Center and Rooms
            </small>
          @enderror

          <!-- <div class="form-group">
            <label for="center_id">Choose Quarantine Center</label>
            <select class="form-control" >
              <option selected>Choose...</option>
              @foreach($centers as $center)
              <option onclick="test()" value="{{$center->id}}">
                {{$center->center_name}}
              </option>
              @endforeach
            </select>
          </div> -->

          <button type="submit" class="btn btn-primary">
            Add New Patient
          </button>
        </form>
      </div>

@endsection

resources/views/dashboard/quser/edit.blade.php
@extends('dashboard.layouts.master')

@section('title', "Dashboard")

@section('content')
<div class="app-page-title">
  <div class="page-title-wrapper">
      <div class="page-title-heading">
          Edit Patient
      </div>
      <div class="page-title-actions">
          <a href="{{route('quarantineUser.index')}}" class="mr-3 btn btn-primary text-light" >
              <i class="pe-7s-back font-size-xl "> </i> Back To Patients List
          </a>
      </div>
  </div>
</div>

  @if ($errors->any())
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
    </div>
@endif

      <div class="col-md-8 offset-md-2  border p-5 mt-5 bg-light">
          <form action="{{route('quarantineUser.update', $quarantineUser->id)}}" method="post" enctype="multipart/form-data">
            @csrf
            @method('patch')
          <div class="form-group">
            <label for="quser_name" class="h5">Patient Name *</label>
            <input type="text" class="form-control @error('quser_name') border border-danger @enderror" id="quser_name" placeholder="Enter Patient Name" name="quser_name" value="{{$quarantineUser->quser_name}}">
            @error("quser_name")
            <small  class="mt-3 form-text text-danger">
              {{ $message }}
            </small>
            @enderror
          </div>

          <img src="{{url('storage/'.str_replace('public/', '', $quarantineUser->profile_image))}}" alt="{{$quarantineUser->quser_name}}" style="width: 70px; height: 70px; display: block; border: 1px solid gray;">
          <label for="image" class="h5 mt-2">Profile Image</label>
          <div class="custom-file mb-3">
            <input type="file" class="custom-file-input" id="validatedCustomFile" name="image">
            <label class="custom-file-label" for="validatedCustomFile">Choose profile...</label>
          </div>

          <div class="form-group">
            <label for="phone" class="h5">Phone No.</label>
            <input type="text" class="form-control @error('phone') border border-danger @enderror" id="phone" placeholder="Enter Phone No." name="phone" value="{{$quarantineUser->phone}}">
            @error("phone")
            <small  class="mt-3 form-text text-danger">
              {{ $message }}
            </small>
            @enderror
          </div>

          <div class="form-group">
            <label for="address" class="h5">Address *</label>
            <textarea name="address" rows="7" class="form-control @error('address') border border-danger @enderror" id="address" placeholder="Enter address">{{$quarantineUser->address}}</textarea>
            @error("address")
            <small  class="mt-3 form-text text-danger">
              {{ $message }}
            </small>
            @enderror
          </div>

          <div class="form-row">
            <div class="col-md-6 mb-3">
              <label for="entry_date">Entry Date *</label>
              <input type="date" class="form-control @error('entry_date') border border-danger @enderror" id="entry_date" name="entry_date" value="{{$quarantineUser->entry_date->format('Y-m-d')}}">
              @error("entry_date")
              <small  class="mt-3 form-text text-danger">
                {{ $message }}
              </small>
              @enderror
            </div>
            <div class="col-md-6 mb-3">
              <label for="leave_date">Leave Date *</label>
              <input type="date" class="form-control @error('leave_date') border border-danger @enderror" id="leave_date" name="leave_date" value="{{$quarantineUser->leave_date->format('Y-m-d')}}">
              @error("leave_date")
              <small  class="mt-3 form-text text-danger">
                {{ $message }}
              </small>
              @enderror
            </div>
          </div>

          <div class="form-group">
            <label for="remark" class="h5">Remark</label>
            <textarea name="remark" rows="7" class="form-control @error('remark') border border-danger @enderror" id="remark" placeholder="Enter remark">{{$quarantineUser->remark}}</textarea>

            @error("remark")
            <small  class="mt-3 form-text text-danger">
              {{ $message }}
            </small>
            @enderror
          </div>


          <div>
            <patient-edit-component :centers="{{$centers}}" :rooms="{{$rooms}}" :centerid="{{$quarantineUser->center_id}}" :roomid="{{$quarantineUser->room_id}}" />
          </div>
          @error("room_id")
            <small  class="mt-3 mb-3 form-text text-danger">
              Choose Center and Rooms
            </small>
          @enderror

          <!-- <div class="form-group">
            <label for="center_id">Choose Quarantine Center</label>
            <select class="form-control" >
              <option selected>Choose...</option>
              @foreach($centers as $center)
              <option onclick="test()" value="{{$center->id}}">
                {{$center->center_name}}
              </option>
              @endforeach
            </select>
          </div> -->

          <button type="submit" class="btn btn-primary">
            Update Patient
          </button>
        </form>
      </div>

@endsection

resources/views/dashboard/quser/index.blade.php
@extends('dashboard.layouts.master')

@section('title', "Dashboard")

@section('content')
<div class="app-page-title">
    <div class="page-title-wrapper">
        <div class="page-title-heading">
            <div>
                Quarantine (Patient) Lists
            </div>
        </div>
        <div class="page-title-actions">
            <a href="{{route('quarantineUser.create')}}" class="mr-3 btn btn-primary text-light" >
                <i class="pe-7s-note font-size-xl "> </i> Add New Parient
            </a>
        </div>
    </div>
</div>

@if (session('store'))
<div class="alert alert-success mb-5 alert-dismissible fade show" role="alert">
  <strong>{{session('store')}}</strong>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
@endif

@if (session('update'))
<div class="alert alert-success mb-5 alert-dismissible fade show" role="alert">
  <strong>{{session('update')}}</strong>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
@endif

@if (session('delete'))
<div class="alert alert-danger mb-5 alert-dismissible fade show" role="alert">
  <strong>{{session('delete')}}</strong>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
@endif

<table id="quarantine_patient" class="table table-striped table-bordered mt-4 mb-4" style="width:100%">
    <thead>
      <tr>
        <th>ID</th>
        <th>Profile</th>
        <th>Patients Name</th>
        <th>Phone</th>
        <th>Address</th>
        <th>Entry Date</th>
        <th>Leave Date</th>
        <th>Remark</th>
        <th>Room No.</th>
        <th>Center</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
        @foreach($quarantine_patients as $quarantine_patient)
        <tr>
            <td>{{$quarantine_patient->id}}</td>
            <td>
                <img src="{{url('storage/'.str_replace('public/', '', $quarantine_patient->profile_image))}}" alt="{{$quarantine_patient->quser_name}}" style="width: 70px; height: 70px">
            </td>
            <td>{{$quarantine_patient->quser_name}}</td>
            <td>{{$quarantine_patient->phone}}</td>
            <td>{{$quarantine_patient->address}}</td>
            <td>{{$quarantine_patient->entry_date->format('d/m/Y')}}</td>
            <td>{{$quarantine_patient->leave_date->format('d/m/Y')}}</td>
            <td>{{$quarantine_patient->remark}}</td>
            <td>{{$quarantine_patient->room->room_name}}</td>
            <td>{{$quarantine_patient->center->center_name}}</td>
            <td>
                <a href="{{route('quarantineUser.show', $quarantine_patient->id)}}" class="ml-3 text-info h4" title="Show Patient">
                    <i class="pe-7s-monitor"> </i>
                </a> <br>
                <a href="{{route('quarantineUser.edit', $quarantine_patient->id)}}" class="ml-3 text-info font-size-lg" title="Edit Patient">
                    <i class="pe-7s-note2"> </i>
                </a> <br>
                <form action="{{ route('quarantineUser.destroy', $quarantine_patient->id) }}" onsubmit="return confirm('{{ 'Are You Sure' }}');" method="POST" class="d-inline">
                  @csrf
                  @method('DELETE')
                  <button type="submit" class="btn btn-link" title="Delete Patient">
                    <i class="metismenu-icon pe-7s-trash h5 text-danger" ></i>
                  </button>
              </form>
            </td>
        </tr>
        @endforeach
    </tbody>
    <tfoot>
    <tr>
        <th>ID</th>
        <th>Profile</th>
        <th>Patients Name</th>
        <th>Phone</th>
        <th>Address</th>
        <th>Entry Date</th>
        <th>Leave Date</th>
        <th>Remark</th>
        <th>Room No.</th>
        <th>Center</th>
        <th>Action</th>
      </tr>
    </tfoot>
  </table>


  @endsection
  @section('script')
  <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
  <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
  <script>
    $(document).ready(function () {
      $('#quarantine_patient').DataTable();
    });
  </script>
  @endsection

resources/views/dashboard/quser/show.blade.php
@extends('dashboard.layouts.master')

@section('title', "Dashboard")

@section('content')
<div class="app-page-title">
  <div class="page-title-wrapper">
      <div class="page-title-heading">
          Quarantine (Patient) Profile
      </div>
      <!-- <div class="page-title-actions">
          <a href="{{route('quarantineUser.index')}}" class="mr-3 btn btn-primary text-light" >
              <i class="pe-7s-back font-size-xl "> </i> Back To Patient List
          </a>
      </div> -->
  </div>
</div>

<div class="row">
  <div class="col-md-3 col-sm-4">
    <div class="card">
      <img src="{{url('storage/'.str_replace('public/', '', $quarantineUser->profile_image))}}" class="card-img-top" alt="{{$quarantineUser->volunteer_name}}">
    </div>
  </div>
  <div class="col-md-8 col-sm-8">
  <div class="main-card mb-3 card">
      <div class="card-header">
          About - {{$quarantineUser->quser_name}}
          <div class="btn-actions-pane-right">

            <!-- @if(now()->diffInDays($quarantineUser->entry_date) ==0)
                <span class="text-success h6">
                    This Patiends entry date is today.
                </span>
            @else
                <span class="text-success h3">
                    {{now()->diffInDays($quarantineUser->entry_date)}} Days
                </span>
            @endif -->
            <span class="text-success h3">
                ({{now()->diffInDays($quarantineUser->leave_date) + 1}}) Left Days
            </span>
          </div>
      </div>
      <div class="table-responsive">
          <table class="align-middle mb-0 table table-borderless table-striped table-hover">
              <thead>

              </thead>
              <tbody>
              <tr>
                    <th>ID</th>
                    <td>#{{$quarantineUser->id}}</t>
                </tr>
              <tr>
                  <th>Patient Name</th>
                  <td>{{$quarantineUser->quser_name}}</t>
              </tr>
              <tr>
                  <th>Phone No.</td>
                  <td>{{$quarantineUser->phone}}</t>
              </tr>
              <tr>
                  <th>Address</td>
                  <td>{{$quarantineUser->address}}</t>
              </tr>
              <tr>
                  <th>Entry Date</td>
                  <td>{{$quarantineUser->entry_date->format('d / m / Y')}}</t>
              </tr>
              <tr>
                  <th>Leave Date</td>
                  <td>{{$quarantineUser->leave_date->format('d / m / Y')}}</t>
              </tr>
              <tr>
                  <th>Remark</td>
                  <td>{{$quarantineUser->remark}}</t>
              </tr>
              <tr>
                  <th>Room No.</td>
                  <td>{{$quarantineUser->room->room_name}}</t>
              </tr>
              <tr>
                  <th>Quarantine Center</td>
                  <td>{{$quarantineUser->center->center_name}}</t>
              </tr>
              <tr>
                  <th>Township</td>
                  <td>{{$quarantineUser->center->township->township_name}}</t>
              </tr>
              <tr>
                  <th>Region / State</td>
                  <td>{{$quarantineUser->center->township->state->state_name}}</t>
              </tr>
              </tbody>
          </table>
      </div>
      <div class="d-block text-center card-footer">
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem sed cum illo quae, asperiores quam voluptates quo assumenda iure eos ducimus sapiente placeat similique molestias in provident error ipsum dicta?</p>
      </div>
  </div>
  </div>
</div>

@endsection