routes/web.php
<?php

use Illuminate\Support\Facades\Route;

// Route::get('/', function () {
//     return view('welcome');
// });

Route::redirect('/', '/dashboard');

Route::middleware(['auth'])->group(function () {
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('/states', 'StateController');
    Route::resource('/townships', 'TownshipController');
    Route::resource('/centers', 'CenterController');
    Route::resource('/rooms', 'RoomController');
    Route::resource('/quarantineUser', 'QuarantineUserController');
    Route::resource('/volunteers', 'VolunteerController');
    Route::resource('/ondutys', 'OndutyController');
    Route::resource('/dutyOffs', 'DutyOffController');

    Route::get('/dashboard/state/{state}', 'DashboardController@state')->name('state');
    Route::get('/dashboard/township/{township}', 'DashboardController@township')->name('township');
    Route::get('/dashboard/center/{center}', 'DashboardController@center')->name('center');

    Route::get('/dashboard/center/{center}/patient', 'DashboardController@patient')->name('patient');
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/test', function () {
    $volunteers = App\Volunteer::unique();

    dd($volunteers);

});

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Center;
use App\QuarantineUser;
use App\Room;
use App\State;
use App\Township;
use App\Volunteer;

class DashboardController extends Controller
{
    public function index()
    {
        $states = State::all();

        $township = Township::all();
        $center = Center::all();
        $room = Room::all();
        $patient = QuarantineUser::all();
        $volunteer = Volunteer::all();

        return view('dashboard.index', [
            'states' => $states,
            'township' => count($township),
            'center' => count($center),
            'room' => count($room),
            'patient' => count($patient),
            'volunteer' => count($volunteer),
        ]);
    }

    public function state($state)
    {
        $townships = Township::where('state_id', $state)->get();

        $state = State::find($state);

        return view('dashboard.township', [
            'state' => $state,
            'townships' => $townships,
        ]);
    }

    public function township($township)
    {
        $centers = Center::where('township_id', $township)->get();

        $township = Township::find($township);

        return view('dashboard.center', [
            'centers' => $centers,
            'township' => $township,
        ]);

    }

    public function center($center)
    {
        $rooms = Room::where('center_id', $center)->get();

        $volunteers = Volunteer::where('center_id', $center)->get();

        $patients = QuarantineUser::where('center_id', $center)->get();

        $center = Center::find($center);

        return view('dashboard.singleCenter', [
            'rooms' => $rooms,
            'volunteers' => $volunteers,
            'center' => $center,
            'patients' => $patients,
        ]);
    }

    public function patient($center)
    {
        $quarantine_patients = QuarantineUser::FilterOn()->where('center_id', $center)->get();

        $center = Center::find($center);
        return view('dashboard.singlePatient', [
            'quarantine_patients' => $quarantine_patients,
            'center' => $center,
        ]);
    }
}

resources/views/dashboard/layouts/footer.blade.php
<div class="app-wrapper-footer">
    <div class="app-footer">
        <div class="app-footer__inner">
            <div class="app-footer-left">
                <ul class="nav">
                    <li class="nav-item">
                        <a href="javascript:void(0);" class="nav-link">
                            Footer Link 1
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="javascript:void(0);" class="nav-link">
                            Footer Link 2
                        </a>
                    </li>
                </ul>
            </div>
            <div class="app-footer-right">
                <ul class="nav">
                    <li class="nav-item">
                        <a href="javascript:void(0);" class="nav-link">
                            Footer Link 3
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="javascript:void(0);" class="nav-link">
                            <div class="badge badge-success mr-1 ml-0">
                                <small>NEW</small>
                            </div>
                            Footer Link 4
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

resources/views/dashboard/layouts/header.blade.php
<div class="app-header header-shadow bg-light header-text-dark">
  <div class="app-header__logo">
      <div class="logo-src"></div>
      <div class="header__pane ml-auto">
          <div>
              <button type="button" class="hamburger close-sidebar-btn hamburger--elastic" data-class="closed-sidebar">
                  <span class="hamburger-box">
                      <span class="hamburger-inner"></span>
                  </span>
              </button>
          </div>
      </div>
  </div>
  <div class="app-header__mobile-menu">
      <div>
          <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
              <span class="hamburger-box">
                  <span class="hamburger-inner"></span>
              </span>
          </button>
      </div>
  </div>
  <div class="app-header__menu">
      <span>
          <button type="button" class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
              <span class="btn-icon-wrapper">
                  <i class="fa fa-ellipsis-v fa-w-6"></i>
              </span>
          </button>
      </span>
  </div>
  <div class="app-header__content">
    <div class="app-header-right">
      <!-- <div class="search-wrapper">
          <div class="input-holder">
              <input type="text" class="search-input" placeholder="Type to search">
              <button class="search-icon"><span></span></button>
          </div>
          <button class="close"></button>
      </div> -->
      <ul class="header-menu nav">
          <!-- <li class="nav-item">
              <a href="javascript:void(0);" class="nav-link">
                  <i class="nav-link-icon fa fa-database"> </i>
                  Statistics
              </a>
          </li>
          <li class="btn-group nav-item">
              <a href="javascript:void(0);" class="nav-link">
                  <i class="nav-link-icon fa fa-edit"></i>
                  Projects
              </a>
          </li> -->
          <li class="dropdown nav-item">
              <span class="nav-link">
              {{ Auth::user()->name }}
              </span>
          </li>
          <li class="dropdown nav-item">
              <a href="#" class="nav-link">
                  <i class="nav-link-icon fa fa-cog"></i>
                  Settings
              </a>
          </li>
          <li class="dropdown nav-item">
                <a class="nav-link"
                    href="{{ route('logout') }}"
                    onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();"
                >
                  <i class="nav-link-icon fas fa-sign-out-alt"></i>
                  {{ __('Logout') }}
              </a>
              <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
          </li>
      </ul>
    </div>
    <!-- <div class="app-header-right">
      <div class="header-btn-lg pr-0">
          <div class="widget-content p-0">
              <div class="widget-content-wrapper">
                  <div class="widget-content-left">
                      <span class="mr-2 text-primary">
                      {{ Auth::user()->name }}
                      </span>
                      <a href=""><i class="pe-7s-next-2"> </i> logout</a>
                      <div class="btn-group">
                          <a data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="p-0 btn">
                              <img width="42" class="rounded-circle" src="assets/images/avatars/1.jpg" alt="">
                              <i class="fa fa-angle-down ml-2 opacity-8"></i>
                          </a>
                          <div tabindex="-1" role="menu" aria-hidden="true" class="dropdown-menu dropdown-menu-right">
                              <button type="button" tabindex="0" class="dropdown-item">User Account</button>
                              <button type="button" tabindex="0" class="dropdown-item">Settings</button>
                              <div tabindex="-1" class="dropdown-divider"></div>
                              <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>
                              <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    </div> -->
  </div>
</div>

resources/views/dashboard/layouts/master.blade.php
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Language" content="en">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>@yield("title")</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no" />
    <meta name="description" content="Description Content">
    <meta name="msapplication-tap-highlight" content="no">

    <!-- Architech Ui CSS -->
    <link href="{{asset('main.css')}}" rel="stylesheet">
    <link rel="stylesheet" href="{{asset('css/app.css')}}">
  </head>
<body>
    <div id="app" class="app-container app-theme-white body-tabs-shadow fixed-sidebar fixed-header">
        @include('dashboard.layouts.header')
        @include('dashboard.layouts.settings')

        <div class="app-main bg-light">
                @include('dashboard.layouts.sidebar')
                <div class="app-main__outer">
                    <div class="app-main__inner border">
                        @yield('content')
                    </div>
                    @include('dashboard.layouts.footer')
                </div>
        <script src="http://maps.google.com/maps/api/js?sensor=true"></script>
        </div>
    </div>
    <script src="{{asset('js/app.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/scripts/main.js')}}"></script>
    </body>
    @yield('script')
</html>

resources/views/dashboard/layouts/sidebar.blade.php
<div class="app-sidebar sidebar-shadow bg-night-sky sidebar-text-light">
    <div class="app-header__logo">
        <div class="logo-src"></div>
        <div class="header__pane ml-auto">
            <div>
                <button type="button" class="hamburger close-sidebar-btn hamburger--elastic" data-class="closed-sidebar">
                    <span class="hamburger-box">
                        <span class="hamburger-inner"></span>
                    </span>
                </button>
            </div>
        </div>
    </div>
    <div class="app-header__mobile-menu">
        <div>
            <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                <span class="hamburger-box">
                    <span class="hamburger-inner"></span>
                </span>
            </button>
        </div>
    </div>
    <div class="app-header__menu">
        <span>
            <button type="button" class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
                <span class="btn-icon-wrapper">
                    <i class="fa fa-ellipsis-v fa-w-6"></i>
                </span>
            </button>
        </span>
    </div>
    <div class="scrollbar-sidebar">
        <div class="app-sidebar__inner">
            <ul class="vertical-nav-menu">
                <li class="app-sidebar__heading">Dashboards</li>
                <li>
                    <a href="{{route('dashboard')}}" class="{{Request::path() === 'dashboard' ? 'mm-active' : '' }}">
                        <i class="metismenu-icon pe-7s-note2"></i>
                        Dashboard
                    </a>
                </li>
                <li class="app-sidebar__heading">Admin Panel</li>
                <li>
                    <a href="{{route('states.index')}}" class="{{Request::path() === 'states' ? 'mm-active' : '' }}">
                        <i class="metismenu-icon pe-7s-network"></i>
                        Region / State
                    </a>
                </li>
                <!-- <li class="app-sidebar__heading">TownShips</li> -->
                <li>
                    <a href="{{route('townships.index')}}" class="{{Request::path() === 'townships' ? 'mm-active' : '' }}">
                        <i class="metismenu-icon pe-7s-culture"></i>
                        Townships
                    </a>
                </li>
                <!-- <li class="app-sidebar__heading">Quarantine Center</li> -->
                <li>
                    <a href="{{route('centers.index')}}" class="{{Request::path() === 'centers' ? 'mm-active' : '' }}" >
                        <i class="metismenu-icon pe-7s-id"></i>
                        Quarantine Centers
                    </a>
                </li>
                <!-- <li class="app-sidebar__heading">Quarantine Room</li> -->
                <li>
                    <a href="{{route('rooms.index')}}" class="{{Request::path() === 'rooms' ? 'mm-active' : '' }}" >
                        <i class="metismenu-icon pe-7s-plugin"></i>
                        Quarantine Rooms
                    </a>
                </li>
                <li class="app-sidebar__heading">Quarantine (Patient)</li>
                <li>
                    <a href="{{route('quarantineUser.index')}}" class="{{Request::path() === 'quarantine_patients' ? 'mm-active' : '' }}" >
                        <i class="metismenu-icon pe-7s-user"></i>
                        Quarantine (Patients)
                    </a>
                </li>
                <li class="app-sidebar__heading">Quarantine (Volunteer)</li>
                <li>
                    <a href="{{route('volunteers.index')}}" class="{{Request::path() === 'volunteers' ? 'mm-active' : '' }}" >
                        <i class="metismenu-icon pe-7s-users"></i>
                        Quarantine (Volunteers)
                    </a>
                </li>
                <li>
                    <a href="{{route('ondutys.create')}}" class="{{Request::path() === 'ondutys/create' ? 'mm-active' : '' }}" >
                        <i class="metismenu-icon pe-7s-paperclip"></i>
                        Add OnDuty
                    </a>
                </li>
                <li>
                    <a href="{{route('dutyOffs.create')}}" class="{{Request::path() === 'dutyoffs/create' ? 'mm-active' : '' }}" >
                        <i class="metismenu-icon pe-7s-paperclip"></i>
                        Add Duty Off
                    </a>
                </li>

                <!-- <li class="app-sidebar__heading">Region / State</li>
                <li>
                    <a href="#">
                        <i class="metismenu-icon pe-7s-diamond"></i>
                        Region / State
                        <i class="metismenu-state-icon pe-7s-angle-down caret-left"></i>
                    </a>
                    <ul>
                        <li>
                            <a href="elements-buttons-standard.html">
                                <i class="metismenu-icon"></i>
                                Region / State List
                            </a>
                        </li>
                        <li>
                            <a href="elements-dropdowns.html">
                                <i class="metismenu-icon">
                                </i>Dropdowns
                            </a>
                        </li>
                        <li>
                            <a href="elements-icons.html">
                                <i class="metismenu-icon">
                                </i>Icons
                            </a>
                        </li>
                        <li>
                            <a href="elements-badges-labels.html">
                                <i class="metismenu-icon">
                                </i>Badges
                            </a>
                        </li>
                        <li>
                            <a href="elements-cards.html">
                                <i class="metismenu-icon">
                                </i>Cards
                            </a>
                        </li>
                        <li>
                            <a href="elements-list-group.html">
                                <i class="metismenu-icon">
                                </i>List Groups
                            </a>
                        </li>
                        <li>
                            <a href="elements-navigation.html">
                                <i class="metismenu-icon">
                                </i>Navigation Menus
                            </a>
                        </li>
                        <li>
                            <a href="elements-utilities.html">
                                <i class="metismenu-icon">
                                </i>Utilities
                            </a>
                        </li>
                    </ul>
                </li> -->
            </ul>
        </div>
    </div>
</div>